# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    # gaps_in = 0
    # gaps_out = 0
    # border_size = 0

    # Change to niri-like side-scrolling layout
    # layout = scrolling
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    rounding = 0

    # Dim unfocused windows (0.0 = no dim, 1.0 = fully dimmed)
    # dim_inactive = true
    # dim_strength = 0.15
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    # Disable all animations
    # enabled = no
}

# https://wiki.hypr.land/Configuring/Variables/#layout
layout {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
}

workspace = special:obsidian, on-created-empty:obsidian
workspace = special:anki, on-created-empty:anki
workspace = special:spotify-launcher, on-created-empty:spotify-launcher

workspace = 1,monitor:DP-1
workspace = 2,monitor:DP-1
workspace = 3,monitor:DP-1
workspace = 4,monitor:DP-1
workspace = 5,monitor:DP-1
workspace = 6,monitor:DP-1
workspace = 7,monitor:DP-1
workspace = 8,monitor:HDMI-A-1
workspace = 9,monitor:HDMI-A-1
workspace = 0,monitor:HDMI-A-1

#workspace = 2,layout:scrolling

windowrule {
    name = subminer-launcher
    match:class = subminer-launcher
    float = on
    size = 1400 900
    center = on
}

windowrule = float on, match:class SubMiner
windowrule = border_size 0, match:class SubMiner
windowrule = xray off override, match:class SubMiner
windowrule = no_shadow on, match:class SubMiner
windowrule = no_blur on, match:class SubMiner

#windowrule = float on, match:initialClass obsidian
#windowrule = size 70% 75%, match:class obsidian
#windowrule = center, match:class obsidian
windowrule {
    name = spotify-launcher
    match:class = spotify-launcher

    float = true
    size = 1400 900
    center = true
}
windowrule {
    name = obsidian
    match:class = obsidian

    float = true
    size = 1400 900
    center = true
}


windowrule {
    name = timew_stats
    match:class = timew-stats
    float = on
    size = 650 900
    center = on
}
windowrule {
    name = timew-month
    match:class = timew-month
    float = on
    size = 1170 840
    center = on
}

windowrule {
    name = myscript-float
    match:class = myscript-float
    float = on
    size = 650 700
    center = on
}

windowrule = tile on, match:class ^(org\.wezfurlong\.wezterm)$

windowrule = rounding 12, match:class ^(org\.gnome\.)

windowrule = tile on, match:class ^(gnome-control-center)$
windowrule = tile on, match:class ^(pavucontrol)$
windowrule = tile on, match:class ^(nm-connection-editor)$

windowrule = float on, match:class ^(org\.gnome\.Calculator)$
windowrule = float on, match:class ^(gnome-calculator)$
windowrule = float on, match:class ^(galculator)$
windowrule = float on, match:class ^(blueman-manager)$
#windowrule = float on, match:class ^(org\.gnome\.Nautilus)$
windowrule = float on, match:class ^(xdg-desktop-portal)$

windowrule = no_initial_focus on, match:class ^(steam)$, match:title ^(notificationtoasts)
windowrule = pin on, match:class ^(steam)$, match:title ^(notificationtoasts)

windowrule = float on, match:class ^(firefox)$, match:title ^(Picture-in-Picture)$
windowrule = float on, match:class ^(zoom)$
