# See https://wiki.hyprland.org/Configuring/Monitors/
# List current monitors and resolutions possible: hyprctl monitors
# Format: monitor = [port], resolution, position, scale

monitor=DP-1,1920x1080@164.0,1920x730,1.0,bitdepth,10
monitor=HDMI-A-1,1920x1080@75.0,3840x730,1.0
monitor=HDMI-A-1,transform,2

# Optimized for retina-class 2x displays, like 13" 2.8K, 27" 5K, 32" 6K.
env = GDK_SCALE,2

